version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    rust: "latest"
  jobs:
    post_install:
      - pip install uv
      - uv pip install -r docs-requirements.txt
    build:
      html:
        - mkdocs build -d $READTHEDOCS_OUTPUT/html
